export const LOADING = 'LOADING'
export const MODE_TOGGLE = 'MODE_TOGGLE'
export const ADD_TO_CART = 'ADD_TO_CART'
export const ADD_TO_LIKED_LIST = 'ADD_TO_LIKED_LIST'
export const REMOVE_FROM_LIKED_LIST = 'REMOVE_FROM_LIKED_LIST'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

